r0_cisco[0]="r0_r5"
r0_cisco[1]="r0_inet"
r0_cisco[2]="r0_r4"
r0_cisco[image]="kathara/quagga"

r4_cisco[0]="r0_r4"
r4_cisco[1]="r4_r3"
r4_cisco[2]="r4_r2"
r4_cisco[3]="r4_r1"
r4_cisco[image]="kathara/quagga"

r1_linux[0]="r1_r2"
r1_linux[1]="r1_pc7"
r1_linux[2]="r4_r1"
r1_linux[image]="kathara/quagga"

r2_linux[0]="r2_pc6"
r2_linux[1]="r4_r2"
r2_linux[2]="r1_r2"
r2_linux[image]="kathara/quagga"

r3_linux[0]="r4_r3"
r3_linux[1]="r3_pc5"
r3_linux[image]="kathara/quagga"

r5_linux[0]="r5_pc4"
r5_linux[1]="r5_pc0"
r5_linux[2]="r0_r5"
r5_linux[image]="kathara/quagga"

internet_cisco[0]="r0_inet"

pc0[0]="r5_pc0"
pc4[0]="r5_pc4"
pc5[0]="r3_pc5"
pc6[0]="r2_pc6"
pc7[0]="r1_pc7"