ns_root[0]="nsroot_r6"
r6[0]="nsroot_r6"

r6[1]="r6_r5"
r6[2]="r6_r4"
r6[3]="r6_r3"

r5[0]="r6_r5"
r5[1]="nsnet_r5"
r5[2]="r5_r2"
ns_net[0]="nsnet_r5"

r2[0]="r5_r2"
r2[1]="webserver_r2"
webserver[0]="webserver_r2"
r2[2]="nsjyu_net_r2"
ns_jyu_net[0]="nsjyu_net_r2"

r4[0]="r6_r4"
r4[1]="nsfi_r4"
ns_fi[0]="nsfi_r4"
r4[2]="r4_pc2"
pc2[0]="r4_pc2"

r3[0]="r6_r3"
r3[1]="nsorg_r3"
ns_org[0]="nsorg_r3"
r3[2]="r3_r1"

r1[0]="r3_r1"
r1[1]="nsjyu_org_r1"
ns_jyu_org[0]="nsjyu_org_r1"
r1[2]="r1_pc1"
pc1[0]="r1_pc1"

ns_root[image]="kathara/bind:9.11"
ns_org[image]="kathara/bind:9.11"
ns_net[image]="kathara/bind:9.11"
ns_fi[image]="kathara/bind:9.11"
ns_jyu_org[image]="kathara/bind:9.11"
ns_jyu_net[image]="kathara/bind:9.11"
pc1[image]="kathara/base"
pc2[image]="kathara/base"
webserver[image]="kathara/base"
